name: Resume Generator
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g resume-cli
      - run: npm install jsonresume-theme-stackoverflow
      - run: resume export index.html
      - run: resume export resume.pdf
      - name: Create release for tags
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./resume.pdf
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate Resume
          branch: master
          file_pattern: resume.pdf index.html
          status_options: '--untracked-files=no'