name: Resume Generator
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install -g resume-cli
      - run: npm install jsonresume-theme-even
      - run: resume export index.html
